### ISSUE TITLE
Reduce tarball size

### ISSUE THREAD

**Issue by PVince81** [owncloud/twofactor_totp#105] opened 2019-03-07 14:01 UTC
The tarball is too big, about 13 MB.

It seems that some composer dependencies are including data files.

We should investigate whether said files are really necessary for the functionality of this app.

**Comment by karakayasemi** [comment] 2019-03-08 16:21
I investigated tarball. The problem is this font file in `endroid/qr-code` dependency: https://github.com/endroid/qr-code/blob/master/assets/fonts/noto_sans.otf (15.7 Mb). 
Looks like it is necessary for qr-code. I guess, there is nothing to do except changing dependency, we can close this ticket.

**Comment by PVince81** [comment] 2019-03-14 08:55
I don't really get why a QR code generator would require fonts, unless it's rendering text in the middle of the QR code in a fancy manner... Are we using this text feature ? If not we should look into switching to a small library then. (future task)

**Closed** 2020-03-23 10:07 UTC
